import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useProfile } from '@/hooks/useProfile';

export type Language = 'es' | 'en' | 'fr' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isLoading: boolean;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'editor.on': 'Activado',
    'editor.off': 'Desactivado',
    'editor.design': 'Diseño',
    'editor.rules': 'Reglas',
    'editor.preview': 'Previsualizar',
    'editor.save': 'Guardar',
    'editor.sidebar.create_popup': 'Crear Banner',
    'editor.sidebar.no_popups': 'No hay banners creados',
    'dashboard.search_popups': 'Buscar banners...',
    'branding.branding': 'Branding',
    'editor.modal': 'Modal',
    'editor.banner': 'Banner',
    'editor.project_updated': 'Proyecto actualizado',
    'editor.project_update_error': 'Error al actualizar proyecto',
    'editor.popup_execute_error': 'Error al ejecutar banner',
    'banners.title': 'Banners y Popups',
    'banners.description': 'Administra tus anuncios de alta conversión y barras de marketing.',
    'banners.install_script': 'Instalar Script',
    'banners.new_banner': 'Nuevo Banner',
    'banners.active': 'Activo',
    'banners.draft': 'Borrador',
    'banners.updated': 'Actualizado',
    'banners.edit': 'Editar',
    'banners.empty.title': 'Tu primer banner está listo',
    'banners.empty.description': 'Potencia tus conversiones en minutos. Crea popups, barras de descuento y anuncios inteligentes.',
    'banners.empty.button': 'Crear Primer Banner',
    'banners.powered_by': 'Potenciado por',
    'banners.delete.title': '¿Estás absolutamente seguro?',
    'banners.delete.description': 'Esta acción no se puede deshacer. Esto eliminará permanentemente tu banner y todos los datos asociados de nuestros servidores.',
    'banners.delete.cancel': 'Cancelar',
    'banners.delete.confirm': 'Eliminar Banner',
    'banners.install.header': 'Instalar Script — {appName}',
    'banners.install.paste_once': 'Pega esto una vez en el {headTag} de tu sitio web. Este único script controla {allPopups} para este proyecto.',
    'banners.install.all_popups': 'todos los popups',
    'banners.install.embed_code': 'CÓDIGO DE INSERCIÓN',
    'banners.install.domain_message': 'Este script funciona automáticamente en {domain} y todos sus subdominios (ej., app.{domain}, blog.{domain}).',
    'banners.install.copy_button': 'Copiar Script',
    'banners.install.copied': 'Script copiado al portapapeles',
    'editor.banner_updated': 'Banner actualizado',
    'editor.banner_update_error': 'Error al actualizar banner',
    'editor.changes_saved': 'Cambios guardados',
    'editor.save_error': 'Error al guardar cambios',
    'editor.banner_activated': 'Banner activado',
    'editor.banner_deactivated': 'Banner desactivado',
    'editor.status_update_error': 'Error al actualizar estado',
    'editor.banner_deleted': 'Banner eliminado',
    'editor.banner_delete_error': 'Error al eliminar banner',
    'editor.sidebar.select_popup': 'Selecciona un banner para comenzar a editar',
    'editor.popup.rename': 'Renombrar',
    'editor.popup.activate': 'Activar',
    'editor.popup.deactivate': 'Desactivar',
    'editor.popup.delete': 'Eliminar',
    'editor.popup.scheduled': 'Programado',
    'editor.popup': 'Popup',
    'banners.your_app': 'Tu Aplicación',
    'editor.sidebar.content': 'Contenido',
    'editor.sidebar.title': 'Título',
    'editor.sidebar.title_placeholder': 'Escribe el título...',
    'editor.sidebar.subtitle': 'Subtítulo',
    'editor.sidebar.subtitle_placeholder': 'Escribe el subtítulo...',
    'editor.sidebar.appearance': 'Apariencia',
    'editor.sidebar.size': 'Tamaño',
    'editor.sidebar.small': 'Pequeño',
    'editor.sidebar.medium': 'Mediano',
    'editor.sidebar.large': 'Grande',
    'editor.sidebar.custom': 'Personalizado',
    'editor.sidebar.width': 'Ancho',
    'editor.sidebar.height': 'Alto',
    'editor.sidebar.position': 'Posición',
    'editor.sidebar.top': 'Superior',
    'editor.sidebar.fixed': 'Fijo',
    'editor.background': 'Fondo',
    'editor.sidebar.overlay': 'Superposición',
    'editor.sidebar.font': 'Fuente',
    'editor.sidebar.download_font': 'Descargar Fuente',
    'editor.sidebar.radius': 'Radio de Borde',
    'editor.sidebar.padding': 'Padding',
    'editor.sidebar.bottom': 'Inferior',
    'editor.animation.slide_up': 'Deslizar ↑',
    'editor.animation.slide_down': 'Deslizar ↓',
    'editor.ai.generate': 'Generar con IA',
    'editor.ai.assistant': 'Asistente IA',
    'editor.ai.clear_history': 'Limpiar historial',
    'editor.ai.description_prompt': 'Describe el banner que necesitas:',
    'editor.ai.sample_maintenance': '"Banner de mantenimiento para lunes de 9am a 4pm"',
    'editor.ai.sample_discount': '"Modal de suscripción con 20% de descuento"',
    'editor.ai.sample_urgent': '"Hazlo más urgente con fondo rojo"',
    'editor.ai.placeholder': 'Describe el banner...',
    'editor.ai.config_applied': 'Configuración aplicada',
    'editor.ai.error': 'Error al generar banner',
    'editor.rules.url_targeting': 'Segmentación por URL',
    'editor.rules.all_pages': 'Todas las páginas',
    'editor.rules.specific': 'Páginas específicas',
    'editor.rules.exclude': 'Excluir páginas',
    'editor.rules.exact': 'Exacto',
    'editor.rules.contains': 'Contiene',
    'editor.rules.starts': 'Empieza con',
    'editor.rules.subdomain': 'Segmentación por Subdominio',
    'editor.rules.all_subdomains': 'Todos los subdominios',
    'editor.rules.main_only': 'Solo dominio principal',
    'editor.rules.only_specific': 'Solo subdominios específicos',
    'editor.rules.devices': 'Dispositivos',
    'editor.rules.plan_scale': 'Personalización por dispositivo (Plan Scale)',
    'editor.rules.click_upgrade': 'Haz clic para mejorar tu plan',
    'editor.rules.trigger': 'Disparador',
    'editor.rules.type': 'Tipo',
    'editor.rules.immediate': 'Inmediato',
    'editor.rules.delay': 'Retraso de tiempo',
    'editor.rules.exit_intent': 'Intención de salida',
    'editor.rules.scroll_percent': 'Porcentaje de scroll',
    'editor.rules.sec': 'seg',
    'editor.rules.frequency': 'Frecuencia',
    'editor.rules.always': 'Siempre',
    'editor.rules.once_per_session': 'Una vez por sesión',
    'editor.rules.once_per_day': 'Una vez al día',
    'editor.rules.once_per_week': 'Una vez por semana',
    'editor.rules.once_ever': 'Solo una vez',
    'editor.rules.schedule': 'Programación',
    'editor.rules.plan_startup': 'Programación de Banners (Plan Startup)',
    'editor.rules.enable_schedule': 'Activar programación',
    'editor.rules.start': 'Inicio',
    'editor.rules.end': 'Fin',
    'editor.rules.timezone': 'Zona horaria',
  },
  en: {
    'editor.on': 'ON',
    'editor.off': 'OFF',
    'editor.design': 'Design',
    'editor.rules': 'Rules',
    'editor.preview': 'Preview',
    'editor.save': 'Save',
    'editor.sidebar.create_popup': 'Create Banner',
    'editor.sidebar.no_popups': 'No banners found',
    'dashboard.search_popups': 'Search banners...',
    'branding.branding': 'Branding',
    'editor.modal': 'Modal',
    'editor.banner': 'Banner',
    'editor.project_updated': 'Project updated',
    'editor.project_update_error': 'Error updating project',
    'editor.popup_execute_error': 'Error executing banner',
    'banners.title': 'Banners & Popups',
    'banners.description': 'Manage your high-conversion announcements and marketing bars.',
    'banners.install_script': 'Install Script',
    'banners.new_banner': 'New Banner',
    'banners.active': 'Active',
    'banners.draft': 'Draft',
    'banners.updated': 'Updated',
    'banners.edit': 'Edit',
    'banners.empty.title': 'Your first banner is ready',
    'banners.empty.description': 'Supercharge your conversions in minutes. Create popups, discount bars, and smart announcements.',
    'banners.empty.button': 'Create First Banner',
    'banners.powered_by': 'Powered by',
    'banners.delete.title': 'Are you absolutely sure?',
    'banners.delete.description': 'This action cannot be undone. This will permanently delete your banner and remove all associated data from our servers.',
    'banners.delete.cancel': 'Cancel',
    'banners.delete.confirm': 'Delete Banner',
    'banners.install.header': 'Install Script — {appName}',
    'banners.install.paste_once': 'Paste this once in your website\'s {headTag}. This single script controls {allPopups} for this project.',
    'banners.install.all_popups': 'all popups',
    'banners.install.embed_code': 'EMBED CODE',
    'banners.install.domain_message': 'This script automatically works on {domain} and all subdomains (e.g., app.{domain}, blog.{domain}).',
    'banners.install.copy_button': 'Copy Script',
    'banners.install.copied': 'Script copied to clipboard',
    'editor.banner_updated': 'Banner updated',
    'editor.banner_update_error': 'Error updating banner',
    'editor.changes_saved': 'Changes saved',
    'editor.save_error': 'Error saving changes',
    'editor.banner_activated': 'Banner activated',
    'editor.banner_deactivated': 'Banner deactivated',
    'editor.status_update_error': 'Error updating status',
    'editor.banner_deleted': 'Banner deleted',
    'editor.banner_delete_error': 'Error deleting banner',
    'editor.sidebar.select_popup': 'Select a banner to start editing',
    'editor.popup.rename': 'Rename',
    'editor.popup.activate': 'Activate',
    'editor.popup.deactivate': 'Deactivate',
    'editor.popup.delete': 'Delete',
    'editor.popup.scheduled': 'Scheduled',
    'editor.popup': 'Popup',
    'banners.your_app': 'Your App',
    'editor.sidebar.content': 'Content',
    'editor.sidebar.title': 'Title',
    'editor.sidebar.title_placeholder': 'Enter title...',
    'editor.sidebar.subtitle': 'Subtitle',
    'editor.sidebar.subtitle_placeholder': 'Enter subtitle...',
    'editor.sidebar.appearance': 'Appearance',
    'editor.sidebar.size': 'Size',
    'editor.sidebar.small': 'Small',
    'editor.sidebar.medium': 'Medium',
    'editor.sidebar.large': 'Large',
    'editor.sidebar.custom': 'Custom',
    'editor.sidebar.width': 'Width',
    'editor.sidebar.height': 'Height',
    'editor.sidebar.position': 'Position',
    'editor.sidebar.top': 'Top',
    'editor.sidebar.fixed': 'Fixed',
    'editor.background': 'Background',
    'editor.sidebar.overlay': 'Overlay',
    'editor.sidebar.font': 'Font',
    'editor.sidebar.download_font': 'Download Font',
    'editor.sidebar.radius': 'Border Radius',
    'editor.sidebar.padding': 'Padding',
    'editor.sidebar.bottom': 'Bottom',
    'editor.animation.slide_up': 'Slide ↑',
    'editor.animation.slide_down': 'Slide ↓',
    'editor.ai.generate': 'Generate with AI',
    'editor.ai.assistant': 'AI Assistant',
    'editor.ai.clear_history': 'Clear history',
    'editor.ai.description_prompt': 'Describe the popup you need:',
    'editor.ai.sample_maintenance': '"Maintenance banner for Monday 9am to 4pm"',
    'editor.ai.sample_discount': '"Subscription modal with 20% discount"',
    'editor.ai.sample_urgent': '"Make it more urgent with red background"',
    'editor.ai.placeholder': 'Describe the popup...',
    'editor.ai.config_applied': 'Configuration applied',
    'editor.ai.error': 'Error generating popup',
    'editor.rules.url_targeting': 'URL Targeting',
    'editor.rules.all_pages': 'All pages',
    'editor.rules.specific': 'Specific pages',
    'editor.rules.exclude': 'Exclude pages',
    'editor.rules.exact': 'Exact',
    'editor.rules.contains': 'Contains',
    'editor.rules.starts': 'Starts with',
    'editor.rules.subdomain': 'Subdomain Targeting',
    'editor.rules.all_subdomains': 'All subdomains',
    'editor.rules.main_only': 'Main domain only',
    'editor.rules.only_specific': 'Only specific subdomains',
    'editor.rules.devices': 'Devices',
    'editor.rules.plan_scale': 'Device targeting (Scale Plan)',
    'editor.rules.click_upgrade': 'Click to upgrade your plan',
    'editor.rules.trigger': 'Trigger',
    'editor.rules.type': 'Type',
    'editor.rules.immediate': 'Immediate',
    'editor.rules.delay': 'Time delay',
    'editor.rules.exit_intent': 'Exit intent',
    'editor.rules.scroll_percent': 'Scroll percentage',
    'editor.rules.sec': 'sec',
    'editor.rules.frequency': 'Frequency',
    'editor.rules.always': 'Always',
    'editor.rules.once_per_session': 'Once per session',
    'editor.rules.once_per_day': 'Once per day',
    'editor.rules.once_per_week': 'Once per week',
    'editor.rules.once_ever': 'Once ever',
    'editor.rules.schedule': 'Schedule',
    'editor.rules.plan_startup': 'Banner Scheduling (Startup Plan)',
    'editor.rules.enable_schedule': 'Enable schedule',
    'editor.rules.start': 'Start',
    'editor.rules.end': 'End',
    'editor.rules.timezone': 'Timezone',
  },
  fr: {
    'editor.on': 'Activé',
    'editor.off': 'Désactivé',
    'editor.design': 'Conception',
    'editor.rules': 'Règles',
    'editor.preview': 'Aperçu',
    'editor.save': 'Enregistrer',
    'editor.sidebar.create_popup': 'Créer une bannière',
    'editor.sidebar.no_popups': 'Aucune bannière trouvée',
    'dashboard.search_popups': 'Rechercher des bannières...',
    'branding.branding': 'Image de marque',
    'editor.modal': 'Modal',
    'editor.banner': 'Bannière',
    'editor.project_updated': 'Projet mis à jour',
    'editor.project_update_error': 'Erreur lors de la mise à jour du projet',
    'editor.popup_execute_error': 'Erreur lors de l’exécution de la bannière',
    'banners.title': 'Bannières et Popups',
    'banners.description': 'Gérez vos annonces à haute conversion et vos barres de marketing.',
    'banners.install_script': 'Installer le script',
    'banners.new_banner': 'Nouvelle bannière',
    'banners.active': 'Actif',
    'banners.draft': 'Brouillon',
    'banners.updated': 'Mis à jour',
    'banners.edit': 'Modifier',
    'banners.empty.title': 'Votre première bannière est prête',
    'banners.empty.description': 'Boostez vos conversions en quelques minutes. Créez des popups, des barres de réduction et des annonces intelligentes.',
    'banners.empty.button': 'Créer la première bannière',
    'banners.powered_by': 'Propulsé par',
    'banners.delete.title': 'Êtes-vous absolument sûr ?',
    'banners.delete.description': 'Cette action ne peut pas être annulée. Cela supprimera définitivement votre bannière et toutes les données associées de nos serveurs.',
    'banners.delete.cancel': 'Annuler',
    'banners.delete.confirm': 'Supprimer la bannière',
    'banners.install.header': 'Installer le script — {appName}',
    'banners.install.paste_once': 'Collez ceci une fois dans le {headTag} de votre site web. Ce script unique contrôle {allPopups} pour ce projet.',
    'banners.install.all_popups': 'tous les popups',
    'banners.install.embed_code': 'CODE D\'INTÉGRATION',
    'banners.install.domain_message': 'Ce script fonctionne automatiquement sur {domain} et tous les sous-domaines (ex., app.{domain}, blog.{domain}).',
    'banners.install.copy_button': 'Copier le script',
    'banners.install.copied': 'Script copié dans le presse-papiers',
    'editor.banner_updated': 'Bannière mise à jour',
    'editor.banner_update_error': 'Erreur lors de la mise à jour de la bannière',
    'editor.changes_saved': 'Modifications enregistrées',
    'editor.save_error': 'Erreur lors de l’enregistrement des modifications',
    'editor.banner_activated': 'Bannière activée',
    'editor.banner_deactivated': 'Bannière désactivée',
    'editor.status_update_error': 'Erreur lors de la mise à jour du statut',
    'editor.banner_deleted': 'Bannière supprimée',
    'editor.banner_delete_error': 'Erreur lors de la suppression de la bannière',
    'editor.sidebar.select_popup': 'Sélectionnez une bannière pour commencer l’édition',
    'editor.popup.rename': 'Renommer',
    'editor.popup.activate': 'Activer',
    'editor.popup.deactivate': 'Désactiver',
    'editor.popup.delete': 'Supprimer',
    'editor.popup.scheduled': 'Programmé',
    'editor.popup': 'Popup',
    'banners.your_app': 'Votre Application',
    'editor.sidebar.content': 'Contenu',
    'editor.sidebar.title': 'Titre',
    'editor.sidebar.title_placeholder': 'Entrez le titre...',
    'editor.sidebar.subtitle': 'Sous-titre',
    'editor.sidebar.subtitle_placeholder': 'Entrez le sous-titre...',
    'editor.sidebar.appearance': 'Apparence',
    'editor.sidebar.size': 'Taille',
    'editor.sidebar.small': 'Petit',
    'editor.sidebar.medium': 'Moyen',
    'editor.sidebar.large': 'Grand',
    'editor.sidebar.custom': 'Personnalisé',
    'editor.sidebar.width': 'Largeur',
    'editor.sidebar.height': 'Hauteur',
    'editor.sidebar.position': 'Position',
    'editor.sidebar.top': 'Haut',
    'editor.sidebar.fixed': 'Fixe',
    'editor.background': 'Arrière-plan',
    'editor.sidebar.overlay': 'Superposition',
    'editor.sidebar.font': 'Police',
    'editor.sidebar.download_font': 'Télécharger la police',
    'editor.sidebar.radius': 'Rayon de bordure',
    'editor.sidebar.padding': 'Padding',
    'editor.sidebar.bottom': 'Bas',
    'editor.animation.slide_up': 'Glisser ↑',
    'editor.animation.slide_down': 'Glisser ↓',
    'editor.ai.generate': "Générer avec l'IA",
    'editor.ai.assistant': 'Assistant IA',
    'editor.ai.clear_history': "Effacer l'historique",
    'editor.ai.description_prompt': 'Décrivez le popup dont vous avez besoin :',
    'editor.ai.sample_maintenance': '"Bannière de maintenance pour lundi de 9h à 16h"',
    'editor.ai.sample_discount': '"Modal d\'abonnement avec 20 % de réduction"',
    'editor.ai.sample_urgent': '"Rendez-le plus urgent avec un fond rouge"',
    'editor.ai.placeholder': 'Décrivez le popup...',
    'editor.ai.config_applied': 'Configuration appliquée',
    'editor.ai.error': 'Erreur lors de la génération du popup',
    'editor.rules.url_targeting': 'Ciblage par URL',
    'editor.rules.all_pages': 'Toutes les pages',
    'editor.rules.specific': 'Pages spécifiques',
    'editor.rules.exclude': 'Exclure des pages',
    'editor.rules.exact': 'Exact',
    'editor.rules.contains': 'Contient',
    'editor.rules.starts': 'Commence par',
    'editor.rules.subdomain': 'Ciblage par sous-domaine',
    'editor.rules.all_subdomains': 'Tous les sous-domaines',
    'editor.rules.main_only': 'Domaine principal uniquement',
    'editor.rules.only_specific': 'Uniquement des sous-domaines spécifiques',
    'editor.rules.devices': 'Appareils',
    'editor.rules.plan_scale': "Ciblage par appareil (Plan Scale)",
    'editor.rules.click_upgrade': 'Cliquez pour mettre à jour votre plan',
    'editor.rules.trigger': 'Déclencheur',
    'editor.rules.type': 'Type',
    'editor.rules.immediate': 'Immédiat',
    'editor.rules.delay': 'Délai de temps',
    'editor.rules.exit_intent': 'Intention de sortie',
    'editor.rules.scroll_percent': 'Pourcentage de défilement',
    'editor.rules.sec': 'sec',
    'editor.rules.frequency': 'Fréquence',
    'editor.rules.always': 'Toujours',
    'editor.rules.once_per_session': 'Une fois par session',
    'editor.rules.once_per_day': 'Une fois par jour',
    'editor.rules.once_per_week': 'Une vez par semaine',
    'editor.rules.once_ever': 'Une seule fois',
    'editor.rules.schedule': 'Calendrier',
    'editor.rules.plan_startup': 'Planification des bannières (Plan Startup)',
    'editor.rules.enable_schedule': 'Activer la planification',
    'editor.rules.start': 'Début',
    'editor.rules.end': 'Fin',
    'editor.rules.timezone': 'Fuseau horaire',
  },
  pt: {
    'editor.on': 'LIGADO',
    'editor.off': 'DESLIGADO',
    'editor.design': 'Design',
    'editor.rules': 'Regras',
    'editor.preview': 'Visualizar',
    'editor.save': 'Salvar',
    'editor.sidebar.create_popup': 'Criar Banner',
    'editor.sidebar.no_popups': 'Nenhum banner encontrado',
    'dashboard.search_popups': 'Buscar banners...',
    'branding.branding': 'Branding',
    'editor.modal': 'Modal',
    'editor.banner': 'Banner',
    'editor.project_updated': 'Projeto atualizado',
    'editor.project_update_error': 'Erro ao atualizar projeto',
    'editor.popup_execute_error': 'Erro ao executar banner',
    'banners.title': 'Banners e Popups',
    'banners.description': 'Gerencie seus anúncios de alta conversão e barras de marketing.',
    'banners.install_script': 'Instalar Script',
    'banners.new_banner': 'Novo Banner',
    'banners.active': 'Ativo',
    'banners.draft': 'Rascunho',
    'banners.updated': 'Atualizado',
    'banners.edit': 'Editar',
    'banners.empty.title': 'Seu primeiro banner está pronto',
    'banners.empty.description': 'Aumente suas conversões em minutos. Crie popups, barras de desconto e anúncios inteligentes.',
    'banners.empty.button': 'Criar Primeiro Banner',
    'banners.powered_by': 'Distribuído por',
    'banners.delete.title': 'Você tem certeza absoluta?',
    'banners.delete.description': 'Esta ação não pode ser desfeita. Isso excluirá permanentemente seu banner e removerá todos os dados associados de nossos servidores.',
    'banners.delete.cancel': 'Cancelar',
    'banners.delete.confirm': 'Excluir Banner',
    'banners.install.header': 'Instalar Script — {appName}',
    'banners.install.paste_once': 'Cole isto uma vez no {headTag} do seu site. Este script único controla {allPopups} para este projeto.',
    'banners.install.all_popups': 'todos os popups',
    'banners.install.embed_code': 'CÓDIGO DE INCORPORAÇÃO',
    'banners.install.domain_message': 'Este script funciona automaticamente em {domain} e todos os subdomínios (ex., app.{domain}, blog.{domain}).',
    'banners.install.copy_button': 'Copiar Script',
    'banners.install.copied': 'Script copiado para a área de transferência',
    'editor.banner_updated': 'Banner atualizado',
    'editor.banner_update_error': 'Erro ao atualizar banner',
    'editor.changes_saved': 'Alterações salvas',
    'editor.save_error': 'Erro ao salvar alterações',
    'editor.banner_activated': 'Banner ativado',
    'editor.banner_deactivated': 'Banner desativado',
    'editor.status_update_error': 'Erro ao atualizar status',
    'editor.banner_deleted': 'Banner excluído',
    'editor.banner_delete_error': 'Erro ao excluir banner',
    'editor.sidebar.select_popup': 'Selecione um banner para começar a editar',
    'editor.popup.rename': 'Renomear',
    'editor.popup.activate': 'Ativar',
    'editor.popup.deactivate': 'Desativar',
    'editor.popup.delete': 'Excluir',
    'editor.popup.scheduled': 'Agendado',
    'editor.popup': 'Popup',
    'banners.your_app': 'Seu Aplicativo',
    'editor.sidebar.content': 'Conteúdo',
    'editor.sidebar.title': 'Título',
    'editor.sidebar.title_placeholder': 'Digite o título...',
    'editor.sidebar.subtitle': 'Subtítulo',
    'editor.sidebar.subtitle_placeholder': 'Digite o subtítulo...',
    'editor.sidebar.appearance': 'Aparência',
    'editor.sidebar.size': 'Tamanho',
    'editor.sidebar.small': 'Pequeno',
    'editor.sidebar.medium': 'Médio',
    'editor.sidebar.large': 'Grande',
    'editor.sidebar.custom': 'Personalizado',
    'editor.sidebar.width': 'Largura',
    'editor.sidebar.height': 'Altura',
    'editor.sidebar.position': 'Posição',
    'editor.sidebar.top': 'Superior',
    'editor.sidebar.fixed': 'Fixo',
    'editor.background': 'Plano de Fundo',
    'editor.sidebar.overlay': 'Sobreposição',
    'editor.sidebar.font': 'Fonte',
    'editor.sidebar.download_font': 'Baixar Fonte',
    'editor.sidebar.radius': 'Raio da Borda',
    'editor.sidebar.padding': 'Padding',
    'editor.sidebar.bottom': 'Inferior',
    'editor.animation.slide_up': 'Deslizar ↑',
    'editor.animation.slide_down': 'Deslizar ↓',
    'editor.ai.generate': 'Gerar com IA',
    'editor.ai.assistant': 'Assistente de IA',
    'editor.ai.clear_history': 'Limpar histórico',
    'editor.ai.description_prompt': 'Descreva o popup que você precisa:',
    'editor.ai.sample_maintenance': '"Banner de manutenção para segunda-feira, das 9h às 16h"',
    'editor.ai.sample_discount': '"Modal de assinatura com 20% de desconto"',
    'editor.ai.sample_urgent': '"Torne-o mais urgente com fundo vermelho"',
    'editor.ai.placeholder': 'Descreva o popup...',
    'editor.ai.config_applied': 'Configuração aplicada',
    'editor.ai.error': 'Erro ao gerar o popup',
    'editor.rules.url_targeting': 'Segmentação por URL',
    'editor.rules.all_pages': 'Todas as páginas',
    'editor.rules.specific': 'Páginas específicas',
    'editor.rules.exclude': 'Excluir páginas',
    'editor.rules.exact': 'Exato',
    'editor.rules.contains': 'Contém',
    'editor.rules.starts': 'Começa com',
    'editor.rules.subdomain': 'Segmentação por Subdomínio',
    'editor.rules.all_subdomains': 'Todos os subdomínios',
    'editor.rules.main_only': 'Apenas domínio principal',
    'editor.rules.only_specific': 'Apenas subdomínios específicos',
    'editor.rules.devices': 'Dispositivos',
    'editor.rules.plan_scale': 'Segmentação por dispositivo (Plano Scale)',
    'editor.rules.click_upgrade': 'Clique para atualizar seu plano',
    'editor.rules.trigger': 'Gatilho',
    'editor.rules.type': 'Tipo',
    'editor.rules.immediate': 'Imediato',
    'editor.rules.delay': 'Atraso de tempo',
    'editor.rules.exit_intent': 'Intenção de saída',
    'editor.rules.scroll_percent': 'Porcentagem de rolagem',
    'editor.rules.sec': 'seg',
    'editor.rules.frequency': 'Frequência',
    'editor.rules.always': 'Sempre',
    'editor.rules.once_per_session': 'Uma vez por sessão',
    'editor.rules.once_per_day': 'Uma vez por dia',
    'editor.rules.once_per_week': 'Uma vez por semana',
    'editor.rules.once_ever': 'Apenas uma vez',
    'editor.rules.schedule': 'Agendamento',
    'editor.rules.plan_startup': 'Agendamento de Banners (Plano Startup)',
    'editor.rules.enable_schedule': 'Ativar agendamento',
    'editor.rules.start': 'Início',
    'editor.rules.end': 'Fim',
    'editor.rules.timezone': 'Fuso horário',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'vibecoders_language';

function detectBrowserLanguage(): Language {
  const browserLang = (navigator.language || (navigator as any).userLanguage || 'en').toLowerCase();
  if (browserLang.startsWith('es')) return 'es';
  if (browserLang.startsWith('fr')) return 'fr';
  if (browserLang.startsWith('pt')) return 'pt';
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>(() => {
    // Initial: check localStorage first
    const stored = localStorage.getItem(STORAGE_KEY);
    if (['es', 'en', 'fr', 'pt'].includes(stored || '')) return stored as Language;
    return 'en'; // Force English as default regardless of browser language if no storage exists, as per user request
  });
  const [isLoading, setIsLoading] = useState(true);

  const { profile, loading: profileLoading } = useProfile();

  // Sync with database when profile is loaded
  useEffect(() => {
    if (profileLoading) return;
    
    const profileData = profile as any; // Safe cast for dynamic fields until interface is fully updated
    
    if (profileData?.language && ['es', 'en', 'fr', 'pt'].includes(profileData.language)) {
      setLanguageState(profileData.language as Language);
      localStorage.setItem(STORAGE_KEY, profileData.language);
      setIsLoading(false);
    } else if (profile) {
      // No language set in DB for this profile, save default
      const defaultLang = 'en';
      supabase
        .from('profiles')
        .update({ language: defaultLang })
        .eq('id', profile.id)
        .then(() => {
          setLanguageState(defaultLang);
          localStorage.setItem(STORAGE_KEY, defaultLang);
          setIsLoading(false);
        });
    } else if (!user) {
      setIsLoading(false);
    }
  }, [profile, profileLoading, user]);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);

    // Persist to database if user is authenticated
    if (user) {
      try {
        await supabase
          .from('profiles')
          .update({ language: lang })
          .eq('id', user.id);
      } catch (err) {
        console.error('Error saving language preference:', err);
      }
    }
  }, [user]);

  const t = useCallback((key: string): string => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    
    // Fallback: return the key itself, but maybe slightly cleaner
    // e.g. "editor.sidebar.create_popup" -> "Create Popup"
    const parts = key.split('.');
    const lastPart = parts[parts.length - 1];
    return lastPart
      .replace(/_/g, ' ')
      .replace(/\b\w/g, char => char.toUpperCase());
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isLoading, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
