// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkotnnmrehzqonlyeorv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprb3Rubm1yZWh6cW9ubHllb3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MTQyOTAsImV4cCI6MjA4NTI5MDI5MH0.s0WbMl0Grma_x7lrpsJ2bLf8x81iDvvi0tNaX801DHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url, options) => {
      const response = await fetch(url, options);
      if (!response.ok) {
        try {
          const clonedResponse = response.clone();
          const data = await clonedResponse.json();
          if (data && (data.hint || data.details)) {
            const sanitizedData = { ...data, hint: null, details: null };
            return new Response(JSON.stringify(sanitizedData), {
              status: response.status,
              statusText: response.statusText,
              headers: response.headers
            });
          }
        } catch (e) {
          // Ignore parse errors
        }
      }
      return response;
    }
  }
});